[project]
name = "advent"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "pytest",
    "mypy",
    "watchdog",
    "ruff"
]

[tool.ruff]
exclude = [
    ".git",
    ".venv",
    "node_modules",
]

[tool.mypy]
strict = true